
image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # Hot reload server (not currently in use due to gitpod tcp port challenges)
  - port: 3035
    onOpen: ignore
    visibility: private
  # PostgreSQL server
  - port: 5432
    onOpen: ignore
    visibility: private

tasks:
  - init: >
      bundle install &&
      rake db:create
    command: >
      echo -e "Welcome!\nIf you have not created a project yet you can run this command to do so:\n gem install foreman && bundle install && rails webpacker:install && rails webpacker:install:react && git add -A && git commit -m "Initial scaffolding" && rails webpacker:install:react && rails generate react_on_rails:install && foreman start -f Procfile.dev-hmr" &&
      echo -e "Welcome!\nYou may start the server with: foreman start -f Procfile.dev-hmr" &&
      echo -e "\nEach terminal that needs access to gems will need to run: bundle install.\nEach terminal that needs access to foreman will need to run: gem install foreman"

vscode:
  extensions:
    - rebornix.ruby
